name: Robot Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0.3']
    name: Ruby ${{ matrix.ruby }} for robot
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby 3.0.3
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.3
      - name: Build and test app
        env:
          APP_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
